trigger:
- main

pool:
  vmImage: 'ubuntu 20.04'  # Replace 'your_vm_image' with the appropriate VM image

jobs:
- job: InstallPython
  displayName: 'Install Python 3.12'
  pool:
    vmImage: 'ubuntu 20.04'  # Repeat the VM image definition for the job level

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: |
      # Additional scripts or commands to run after installing Python 3.12
      echo "Python 3.12 installed successfully"
    displayName: 'Post-installation steps'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

  - task: SSH@0
    inputs:
      sshEndpoint: 'FirstProjectServiceConnection'  # Replace 'your_ssh_connection' with the name of your SSH service connection
      runOptions: 'inline'
      inline: 'sudo apt-get update && sudo apt-get install -y python3.12'
    displayName: 'Install Python on Ubuntu'
